

post http://localhost:3000/companies/bureaus/1/companies
Content-Type: application/json

{   
        "bureau_id":1,
        "company_fiscal_id":1,
        "company_name": "b",
        "ssscheme_id":1,
        "company_address":"company_address",
        "postalcode_id":"1",
        "company_city":"company_city",
        "state_id":1,
        "company_phone":"company_phone",
        "company_contact":"company_contact",
        "company_email":"company_email",
        "company_status_id":1,
        "company_certificate": "company_certificate"
}
###

get http://localhost:3000/companies/bureaus/1/companies
Content-Type: application/json

###

post http://localhost:3000/mail
Content-Type: application/json

{
    "mail":"j.cueto@a3satel.com",
    "password":"Pokemons12*"
}

###

post http://localhost:3000/mail/activation
Content-Type: application/json

{
    "mail":"j.cueto@a3satel.com",
    "password":"Pokemons12*",
    "user_full_name":"jesus cueto gonzalez"
}
###
put http://localhost:3000/companies/bureaus/1/companies/6
Content-Type: application/json

{
        "company_fiscal_id":1,
        "company_name": "jose",
        "ssscheme_id":1,
        "company_address":"company_address",
        "company_postal_code":"1123",
        "company_city":"company_city",
        "state_id":1,
        "company_phone":"company_phone",
        "company_contact":"company_contact",
        "company_email":"company_email",
        "company_status_id":1,
        "company_certificate": "company_certificate"
}
###


get http://localhost:3000/users/user/j.cueto@a3satel.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdlIiOiJBM1NBVEVMIiwidXNlcl9pZCI6NCwiYnVyZWF1X2lkIjoxLCJyb2xfaWQiOjEsImlhdCI6MTY3MDkzNzkzNCwiZXhwIjoxNjcwOTM3OTk0fQ.TMMso97pU2gahfUuiPWgibT1LyAvQeILPfFP3k0le7o
###

POST http://localhost:3000/users/bureaus/1/users
Content-Type: application/json

{
   "bureau_id": 1, 
    "user_full_name": "PEREZ LOPEZ", 
    "user_phone": "954276522", 
    "user_email": "ao.perez@elcantaro.es", 
    "user_observation": "", 
    "rol_id": 1,
    "user_password": "A3Satel*2023",
    "status_id": 1
}
###
DELETE  http://localhost:3000/companies/bureaus/1/companies/6/delete

###
POST  http://localhost:3000/users/bureaus/1/invitation
Content-Type: application/json

{
    "user_id": "6"
}
###
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "user_email": "a.perez@elcantaro.es", 
    "user_password": "A3Satel*2023"
}
###
POST  http://localhost:3000/contributionaccountcodes/bureaus/1/companies/2/contributionaccount
Content-Type: application/json

{
    "contributionaccountcode_id":6,
    "contributionaccountcode_code":1
}
