-- MySQL Script generated by MySQL Workbench
-- Tue Dec 20 17:02:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema afilia3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema afilia3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `afilia3` DEFAULT CHARACTER SET utf8 ;
USE `afilia3` ;

-- -----------------------------------------------------
-- Table `afilia3`.`bureaus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afilia3`.`bureaus` (
  `bureau__id` INT NOT NULL AUTO_INCREMENT,
  `bureau_fiscal_Id` VARCHAR(12) NOT NULL,
  `bureau_name` VARCHAR(16) NOT NULL,
  `bureau_observation` BLOB NULL,
  `bureau_status` TINYINT NOT NULL,
  `bureau_create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `bureau_update_time` TIMESTAMP NULL,
  PRIMARY KEY (`bureau__id`));


-- -----------------------------------------------------
-- Table `afilia3`.`rols`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afilia3`.`rols` (
  `rol_id` TINYINT NOT NULL,
  `rol_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`rol_id`));


-- -----------------------------------------------------
-- Table `afilia3`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afilia3`.`status` (
  `status_id` TINYINT NOT NULL,
  `status_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `afilia3`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afilia3`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `bureau_id` INT NOT NULL,
  `user_full_name` VARCHAR(150) NOT NULL,
  `user_phone` VARCHAR(20) NULL,
  `user_observation` BLOB NULL,
  `rol_id` TINYINT NOT NULL,
  `status_id` TINYINT NOT NULL,
  `user_email` VARCHAR(255) NOT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  `user_create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_update_time` TIMESTAMP NULL,
  PRIMARY KEY (`user_id`, `bureau_id`, `rol_id`, `status_id`),
  INDEX `fk_user_bureau_idx` (`bureau_id` ASC) VISIBLE,
  INDEX `fk_user_userType_idx` (`rol_id` ASC) VISIBLE,
  INDEX `fk_user_status1_idx` (`status_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`user_email` ASC) VISIBLE,
  CONSTRAINT `fk_user_bureau`
    FOREIGN KEY (`bureau_id`)
    REFERENCES `afilia3`.`bureaus` (`bureau__id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_userType`
    FOREIGN KEY (`rol_id`)
    REFERENCES `afilia3`.`rols` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_status`
    FOREIGN KEY (`status_id`)
    REFERENCES `afilia3`.`status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `afilia3`.`invitations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afilia3`.`invitations` (
  `user_id` INT NOT NULL,
  `invitation_token` VARCHAR(255) NOT NULL,
  `invitation_create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_invitations_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `afilia3`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `afilia3`.`modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afilia3`.`modules` (
  `module_id` INT NOT NULL,
  `module_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`module_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `afilia3`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afilia3`.`permissions` (
  `permission_id` INT NOT NULL AUTO_INCREMENT,
  `permision_name` VARCHAR(45) NOT NULL,
  `module_id` INT NOT NULL,
  PRIMARY KEY (`permission_id`, `module_id`),
  INDEX `fk_permissions_modules1_idx` (`module_id` ASC) VISIBLE,
  CONSTRAINT `fk_permissions_modules`
    FOREIGN KEY (`module_id`)
    REFERENCES `afilia3`.`modules` (`module_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `afilia3`.`rols_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afilia3`.`rols_permissions` (
  `iduserType_permissions` INT NOT NULL,
  `idPermissions` INT NOT NULL,
  `rol_id` TINYINT NOT NULL,
  PRIMARY KEY (`iduserType_permissions`, `idPermissions`, `rol_id`),
  INDEX `fk_userType_permissions_permissions1_idx` (`idPermissions` ASC) VISIBLE,
  INDEX `fk_userType_permissions_userType1_idx` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_userType_permissions_permissions1`
    FOREIGN KEY (`idPermissions`)
    REFERENCES `afilia3`.`permissions` (`permission_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userType_permissions_userType1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `afilia3`.`rols` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `afilia3`.`refreshtokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afilia3`.`refreshtokens` (
  `refreshtoken_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `refreshtoken_token` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`refreshtoken_id`, `user_id`),
  INDEX `fk_sessions_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_sessions_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `afilia3`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
